<a href="https://colab.research.google.com/github/p9anand/SHALA2020/blob/master/Assignment_1_DS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# **Assignment - 1 : Getting Started**

---

This assignment will get you familiarized with python libraries required for ***data science*** and ***machine learning***. You will have to complete the code snippets and run them. 

## **Note :**   Use only the methods and attributes of the ```numpy``` library. **Do not** hard-code them. Avoid loops as much as possible.

---
## Part - 1
 In this part, you will work with the library ```numpy```. 




Import ```numpy``` with an alias name ```np```. Initialize two arrays $a$, $b$ of size $3 \times 5$ with random values and print them. 

In [11]:
import numpy as np 

a = np.random.rand(3,5)
b = np.random.rand(3,5)
print(a)
print(b)

[[0.50539614 0.31667435 0.46710546 0.95169697 0.54171951]
 [0.01940793 0.25902208 0.67299545 0.236115   0.52731506]
 [0.1087257  0.41667321 0.38597015 0.249662   0.09299636]]
[[0.4090223  0.98075757 0.45185434 0.85413244 0.96380021]
 [0.77423134 0.8891232  0.9548215  0.22319316 0.88937177]
 [0.33281015 0.1823839  0.70343938 0.53856787 0.43906193]]


Initialize and print two arrays $c$ and $d$ having the following properties:
*   $c$ is a row vector with all positive integer values less than 100
* $d$ is a square matrix of size 3 having all entries as 0.0

In [32]:
c = np.random.randint(100, size=(100, ))
print(c)
d = np.zeros(shape=(3,3))
print(d)

[17 62 69 67 47 95  4 71 94 77 82 58 31 15 20 56  6 23 98 39 36  0 41 39
 81 33 83 92 85 39 30 63 84 54 63 13 79 39 32 38 42  6 14 26 50 16 45 53
 93 86 81 83 22 37 37 69 95 36 84 65  3 60 39  2 10 61  9 18 21 27 67 62
 42 82 85  1 29 31 51 37 14 76 81 17 68 45 85  2  0 26 43 48 45 99 46 49
 15 98  9 33]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


We have $e$ as following : ```e = [[1,2,3],[4,5,6],[7,8,9]]```. Change $e$ as a numpy array and print it.

In [19]:
e = [[1,2,3],[4,5,6],[7,8,9]]
e = np.array(e)
print(e)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


$f$ and $g$ are two square matrices of size 5 such that all the entries of $f$ are 1 and $g$ is an identity matrix. Initialize them and print them

In [23]:
f = np.ones(shape=(5, 5))
print(f)
g = np.eye(5)
print(g)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Reshape $c$ into a $10 \times 10$ matrix and name it $h$. Now flatten $h$, call it $c^\prime$ and print **YES** when the shapes of $c$ and $c^\prime$ are same. Otherwise print **NO**.

In [33]:
print(c.shape)
h = np.reshape(c, (10, 10))
print(h)
c_prime = h.flatten()
print(c_prime.shape)

if c_prime.shape==c.shape:
    print('YES')
else:
    print('NO')

(100,)
[[17 62 69 67 47 95  4 71 94 77]
 [82 58 31 15 20 56  6 23 98 39]
 [36  0 41 39 81 33 83 92 85 39]
 [30 63 84 54 63 13 79 39 32 38]
 [42  6 14 26 50 16 45 53 93 86]
 [81 83 22 37 37 69 95 36 84 65]
 [ 3 60 39  2 10 61  9 18 21 27]
 [67 62 42 82 85  1 29 31 51 37]
 [14 76 81 17 68 45 85  2  0 26]
 [43 48 45 99 46 49 15 98  9 33]]
(100,)
YES


Let $A$ denote a randomly initialized three dimensional matrix of shape (2,10,5). Transpose $A$, call it $A^\prime$, such that its shape is (5,2,10) and print it.

In [38]:
A = np.random.rand(2,10,5)
print(A)
A_prime = A.T.reshape((5, 2, 10))
# print(A_prime.reshape((5, 2, 10)))
print(A_prime)

[[[0.2581792  0.33636158 0.128374   0.54430996 0.98433225]
  [0.92932361 0.89459157 0.20055625 0.01457847 0.93735122]
  [0.4086338  0.95301817 0.71604785 0.41011813 0.82013092]
  [0.68887611 0.13052754 0.8159529  0.20600539 0.50998468]
  [0.30862468 0.69275034 0.93714746 0.67367126 0.21495537]
  [0.49467115 0.77958034 0.99970897 0.29651839 0.79620738]
  [0.11367112 0.9889092  0.84460853 0.07438283 0.252587  ]
  [0.36651407 0.10148154 0.8534404  0.15064981 0.58497258]
  [0.92463151 0.82300136 0.32771336 0.10079159 0.06004216]
  [0.0081948  0.92707624 0.60856443 0.65186032 0.27517178]]

 [[0.51610421 0.52968333 0.29781245 0.60968004 0.36200206]
  [0.07837614 0.24117935 0.45302653 0.86784596 0.44436158]
  [0.1193462  0.42230704 0.99548335 0.95954083 0.91320151]
  [0.10957599 0.48606888 0.41215131 0.114983   0.0201487 ]
  [0.90858218 0.13904851 0.3843698  0.77769596 0.10156229]
  [0.68318464 0.76868942 0.45660269 0.5762814  0.42343429]
  [0.33996794 0.56031986 0.61505147 0.68162601 0.55201

You have a matrix $X$ of size (10,5) filled with random values. Print the following :
* Minimum value and index where it occured, for each column
* Maximum value and the index where it occured, for each column
* Minimum value and index where it occured, for each row
* Maximum value and index where it occured, for each row
* Minimum value and index where it occured, for the entire matrix
* Maximum value and index where it occured, for the entire matrix

In [53]:
np.random.seed(0)
X = np.random.rand(10,5)
print(f'Minimum value of array X along columns: {np.amin(X, axis=0)} and corresponding index: {np.argmin(X, axis=0)}')
print('------------')
print(f'Maximum value of array X along columns: {np.amax(X, axis=0)} and corresponding index: {np.argmax(X, axis=0)}')
print('------------')
print(f'Minimum value of array X along row: {np.amin(X, axis=1)} and corresponding index: {np.argmin(X, axis=1)}')
print('------------')
print(f'Maximum value of array X along row: {np.amax(X, axis=1)} and corresponding index: {np.argmax(X, axis=1)}')
print('------------')
print(f'Minimum value of array X overall: {np.amin(X)} and corresponding index: {np.argmin(X)}')
print('------------')
print(f'Maximum value of array X overall: {np.amax(X)} and corresponding index: {np.argmax(X)}')

Minimum value of array X along columns: [0.0871293  0.0202184  0.1289263  0.06022547 0.0187898 ] and corresponding index: [3 3 9 8 6]
------------
Maximum value of array X along columns: [0.97861834 0.79915856 0.94466892 0.96366276 0.87001215] and corresponding index: [4 4 5 1 3]
------------
Minimum value of array X along row: [0.4236548  0.38344152 0.07103606 0.0202184  0.11827443 0.14335329
 0.0187898  0.61209572 0.06022547 0.1289263 ] and corresponding index: [4 4 4 1 4 1 4 1 3 2]
------------
Maximum value of array X along row: [0.71518937 0.96366276 0.92559664 0.87001215 0.97861834 0.94466892
 0.77423369 0.94374808 0.6976312  0.67063787] and corresponding index: [1 3 3 4 0 2 1 3 2 0]
------------
Minimum value of array X overall: 0.018789800436355142 and corresponding index: 34
------------
Maximum value of array X overall: 0.978618342232764 and corresponding index: 20


Find and print the following for the matrix X: 
* Mean of each row and column
* Standard deviation of each row and column
* Mean of the entire matrix
* Standard deviation of entire matrix

In [56]:
print(f'mean of X along row: {X.mean(axis=1)} and along column: {X.mean(axis=0)}')
print(f'standard deviation of X along row: {X.std(axis=1)} and along column: {X.std(axis=0)}')
print(f'mean of the entire matrix is: {X.mean()}')
print(f'standard deviation of entire matrix is: {X.std()}')

mean of X along row: [0.56706085 0.66447172 0.57705944 0.51762729 0.62761197 0.5328907
 0.41643268 0.69444672 0.44423265 0.33781717] and along column: [0.56044382 0.46781457 0.62009909 0.64025127 0.40121685]
standard deviation of X along row: [0.09445299 0.23322986 0.29189733 0.38052993 0.30431633 0.26338419
 0.25841437 0.12727959 0.23169975 0.18537332] and along column: [0.24687647 0.25752158 0.22948615 0.28054144 0.26584905]
mean of the entire matrix is: 0.5379651182755409
standard deviation of entire matrix is: 0.27226582292177587


Let $Y$ denote a square matrix of size 10 with random values. Print the following:
* Determinant
* Rank of the matrix
* Diagonal Elements
* Trace
* Eigen values
* Matrices obtained after Singular Value Decomposition
* Inverse if exists, otherwise Pseudo-Inverse
* Multiplication $Y$ with $X$
* Element-wise multiplication of $Y$ and its inverse(or pseudo-inverse)

In [64]:
np.random.seed(3)
Y = np.random.rand(10,10)
print(f'determinant of Y: {np.linalg.det(Y)}')
print(f'rank of the Y: {np.linalg.matrix_rank(Y)}')
print(f'diagonal elements of matrix Y: {Y.diagonal()}')
print(f'trace of matrix Y: {Y.trace()}')
print(f'eigen values of matrix Y: {np.linalg.eigvals(Y)}')
print(f'matrices obtained after svd: {np.linalg.svd(Y)}')
print(f'inverse of martix Y: {np.linalg.inv(Y)}')
print(f'multiplication of matrix Y with X i.e(Y*X): {np.matmul(Y, X)}')
print(f'Element-wise multiplication of  𝑌  and its inverse(or pseudo-inverse): {np.dot(Y, np.linalg.inv(Y))}')

determinant of Y: -0.012807808169095483
rank of the Y: 10
diagonal elements of matrix Y: [0.5507979  0.45683322 0.44045372 0.84575087 0.4576864  0.36217621
 0.06152893 0.19897603 0.92672568 0.19638058]
trace of matrix Y: 4.497309545724899
eigen values of matrix Y: [ 4.797525  +0.j          0.72411408+0.52238181j  0.72411408-0.52238181j
 -0.48250062+0.55413671j -0.48250062-0.55413671j -0.6909002 +0.j
 -0.25905659+0.32357377j -0.25905659-0.32357377j  0.2127855 +0.08352477j
  0.2127855 -0.08352477j]
matrices obtained after svd: (array([[-0.31776408, -0.02455508, -0.60644878, -0.17883359, -0.12672161,
         0.14873878, -0.17823942, -0.52859453, -0.02295855, -0.38570883],
       [-0.26118514, -0.10864541, -0.24911354,  0.26547359,  0.52168399,
        -0.25773901, -0.46995326,  0.21752636, -0.39285046,  0.16234491],
       [-0.31347907, -0.34483471, -0.25292297,  0.1214296 ,  0.1486964 ,
         0.33436315,  0.54080229,  0.48017168,  0.05660692, -0.20966421],
       [-0.35815379,  0.594

## End of Part - 1
 --- --- ---

## Part - 2
---
In this part, you will be working with the library ```pandas```. Import this library with an alias name ```pd```.

In [0]:
# Initial imports
import numpy as np
import matplotlib.pyplot as plt


Download dataset from: http://biostat.mc.vanderbilt.edu/wiki/pub/Main/DataSets/titanic3.csv
Read the data and display the first 5 rows

In [0]:
#Download dataset from: http://biostat.mc.vanderbilt.edu/wiki/pub/Main/DataSets/titanic3.csv

file_url = "http://biostat.mc.vanderbilt.edu/wiki/pub/Main/DataSets/titanic3.csv"



### Preprocessing of the Dataset



---


**1. Convert the categorical values of columns 'sex', 'embarked', 'pclass' into dummy values and add them into titanic_data_new DataFrame**




---





---


**2. Fill the missing data in Age and Fare columns with the mean value of the respected column then add these columns to titanic_data_new**


---



###Normalization


---



1. Normalize the columns which have numerical data



---





---
2. Drop the original age, fare columns
3. Append the normalized columns to the titanic_data_new DataFrame.



---



###Plotting
1. plot the age against the ID(continuous)
2. plot the fare against the ID(scatter)

## End of Part - 2
---

## Part - 3
---

In this part, you will work with the library ```matplotlib```. Import the ```pyplot``` from ```matplotlib``` with an alias name ```plt```.

Plot the sine function with domain in $[-3\pi,3\pi]$. Label the axes appropriately. Add title $\sin(x)$. Use latex formatting while adding the title. Set the plot size to (10,10)

Plot $\sin(x)$ and its spectrum, $\cos(x)$ and its spectrum in a single plot, in the domain $[-2\pi,2\pi]$. Label the plot appropriately.

## End of Part - 3
---

Create a Github repository with the name ***SHALA2020*** and save this assignment there.