<a href="https://colab.research.google.com/github/p9anand/SHALA2020/blob/master/Assignment_1_DS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# **Assignment - 1 : Getting Started**

---

This assignment will get you familiarized with python libraries required for ***data science*** and ***machine learning***. You will have to complete the code snippets and run them. 

## **Note :**   Use only the methods and attributes of the ```numpy``` library. **Do not** hard-code them. Avoid loops as much as possible.

---
## Part - 1
 In this part, you will work with the library ```numpy```. 




Import ```numpy``` with an alias name ```np```. Initialize two arrays $a$, $b$ of size $3 \times 5$ with random values and print them. 

In [1]:
import numpy as np 

a = np.random.rand(3,5)
b = np.random.rand(3,5)
print(a)
print(b)

[[0.82045275 0.47943976 0.47711277 0.61048685 0.23861697]
 [0.1997782  0.33120015 0.33519406 0.29362207 0.85468042]
 [0.39024494 0.11148004 0.1965106  0.77319691 0.74253275]]
[[0.6575865  0.07023981 0.67174558 0.94708363 0.97028802]
 [0.38805982 0.17823554 0.50744272 0.75723663 0.98341403]
 [0.81847743 0.22060397 0.35795651 0.4226798  0.91496644]]


Initialize and print two arrays $c$ and $d$ having the following properties:
*   $c$ is a row vector with all positive integer values less than 100
* $d$ is a square matrix of size 3 having all entries as 0.0

In [2]:
c = np.random.randint(100, size=(100, ))
print(c)
d = np.zeros(shape=(3,3))
print(d)

[92 10 93 72 12 84 10 29 12 85 12 89  8 24 68 30 61 45 61 86 51 91 33  9
 16 44 50  2 60 88 93 18 74 92 68 45 46 46 38  7  7 27 31 91 12 43 86 89
 41 41 48  6 46 52 46  9 18 30 39 72  5 45  2 10 62 86 18 42 28 87  6  0
  4 73 13  3 53 34 40 27 78 93 69 77 15 85 28  3 27 20 16 66 14 36 74 75
 66 18 50 79]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


We have $e$ as following : ```e = [[1,2,3],[4,5,6],[7,8,9]]```. Change $e$ as a numpy array and print it.

In [3]:
e = [[1,2,3],[4,5,6],[7,8,9]]
e = np.array(e)
print(e)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


$f$ and $g$ are two square matrices of size 5 such that all the entries of $f$ are 1 and $g$ is an identity matrix. Initialize them and print them

In [4]:
f = np.ones(shape=(5, 5))
print(f)
g = np.eye(5)
print(g)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Reshape $c$ into a $10 \times 10$ matrix and name it $h$. Now flatten $h$, call it $c^\prime$ and print **YES** when the shapes of $c$ and $c^\prime$ are same. Otherwise print **NO**.

In [5]:
print(c.shape)
h = np.reshape(c, (10, 10))
print(h)
c_prime = h.flatten()
print(c_prime.shape)

if c_prime.shape==c.shape:
    print('YES')
else:
    print('NO')

(100,)
[[92 10 93 72 12 84 10 29 12 85]
 [12 89  8 24 68 30 61 45 61 86]
 [51 91 33  9 16 44 50  2 60 88]
 [93 18 74 92 68 45 46 46 38  7]
 [ 7 27 31 91 12 43 86 89 41 41]
 [48  6 46 52 46  9 18 30 39 72]
 [ 5 45  2 10 62 86 18 42 28 87]
 [ 6  0  4 73 13  3 53 34 40 27]
 [78 93 69 77 15 85 28  3 27 20]
 [16 66 14 36 74 75 66 18 50 79]]
(100,)
YES


Let $A$ denote a randomly initialized three dimensional matrix of shape (2,10,5). Transpose $A$, call it $A^\prime$, such that its shape is (5,2,10) and print it.

In [6]:
A = np.random.rand(2,10,5)
print(A)
A_prime = A.T.reshape((5, 2, 10))
# print(A_prime.reshape((5, 2, 10)))
print(A_prime)

[[[0.75583069 0.63731663 0.64643269 0.34950429 0.35185043]
  [0.01907073 0.85595561 0.22308593 0.76261161 0.24077169]
  [0.96916065 0.91462896 0.53265398 0.38547977 0.72211728]
  [0.59048343 0.51731464 0.4232958  0.8270779  0.97742095]
  [0.03095787 0.98690406 0.61686898 0.35393797 0.46401177]
  [0.23507874 0.56527617 0.90358457 0.56065124 0.64461716]
  [0.44440959 0.78780151 0.3644425  0.99363006 0.1034506 ]
  [0.81758218 0.73640152 0.45242948 0.56920807 0.86709792]
  [0.96842276 0.40663831 0.85899697 0.98425778 0.1188185 ]
  [0.83945022 0.25490912 0.87932566 0.87299594 0.96125118]]

 [[0.76267815 0.63911858 0.28215218 0.52529103 0.30864279]
  [0.72132473 0.17786909 0.05832565 0.96751907 0.29515615]
  [0.03511974 0.08253276 0.03173348 0.92649851 0.86087444]
  [0.31860737 0.54223868 0.32189153 0.98846497 0.47937682]
  [0.19155592 0.32374169 0.41903145 0.20281722 0.07207588]
  [0.2968703  0.58737076 0.80139616 0.20678682 0.40529458]
  [0.96279912 0.76071442 0.90287492 0.80833768 0.87444

You have a matrix $X$ of size (10,5) filled with random values. Print the following :
* Minimum value and index where it occured, for each column
* Maximum value and the index where it occured, for each column
* Minimum value and index where it occured, for each row
* Maximum value and index where it occured, for each row
* Minimum value and index where it occured, for the entire matrix
* Maximum value and index where it occured, for the entire matrix

In [7]:
np.random.seed(0)
X = np.random.rand(10,5)
print(f'Minimum value of array X along columns: {np.amin(X, axis=0)} and corresponding index: {np.argmin(X, axis=0)}')
print('------------')
print(f'Maximum value of array X along columns: {np.amax(X, axis=0)} and corresponding index: {np.argmax(X, axis=0)}')
print('------------')
print(f'Minimum value of array X along row: {np.amin(X, axis=1)} and corresponding index: {np.argmin(X, axis=1)}')
print('------------')
print(f'Maximum value of array X along row: {np.amax(X, axis=1)} and corresponding index: {np.argmax(X, axis=1)}')
print('------------')
print(f'Minimum value of array X overall: {np.amin(X)} and corresponding index: {np.argmin(X)}')
print('------------')
print(f'Maximum value of array X overall: {np.amax(X)} and corresponding index: {np.argmax(X)}')

Minimum value of array X along columns: [0.0871293  0.0202184  0.1289263  0.06022547 0.0187898 ] and corresponding index: [3 3 9 8 6]
------------
Maximum value of array X along columns: [0.97861834 0.79915856 0.94466892 0.96366276 0.87001215] and corresponding index: [4 4 5 1 3]
------------
Minimum value of array X along row: [0.4236548  0.38344152 0.07103606 0.0202184  0.11827443 0.14335329
 0.0187898  0.61209572 0.06022547 0.1289263 ] and corresponding index: [4 4 4 1 4 1 4 1 3 2]
------------
Maximum value of array X along row: [0.71518937 0.96366276 0.92559664 0.87001215 0.97861834 0.94466892
 0.77423369 0.94374808 0.6976312  0.67063787] and corresponding index: [1 3 3 4 0 2 1 3 2 0]
------------
Minimum value of array X overall: 0.018789800436355142 and corresponding index: 34
------------
Maximum value of array X overall: 0.978618342232764 and corresponding index: 20


Find and print the following for the matrix X: 
* Mean of each row and column
* Standard deviation of each row and column
* Mean of the entire matrix
* Standard deviation of entire matrix

In [8]:
print(f'mean of X along row: {X.mean(axis=1)} and along column: {X.mean(axis=0)}')
print(f'standard deviation of X along row: {X.std(axis=1)} and along column: {X.std(axis=0)}')
print(f'mean of the entire matrix is: {X.mean()}')
print(f'standard deviation of entire matrix is: {X.std()}')

mean of X along row: [0.56706085 0.66447172 0.57705944 0.51762729 0.62761197 0.5328907
 0.41643268 0.69444672 0.44423265 0.33781717] and along column: [0.56044382 0.46781457 0.62009909 0.64025127 0.40121685]
standard deviation of X along row: [0.09445299 0.23322986 0.29189733 0.38052993 0.30431633 0.26338419
 0.25841437 0.12727959 0.23169975 0.18537332] and along column: [0.24687647 0.25752158 0.22948615 0.28054144 0.26584905]
mean of the entire matrix is: 0.5379651182755409
standard deviation of entire matrix is: 0.27226582292177587


Let $Y$ denote a square matrix of size 10 with random values. Print the following:
* Determinant
* Rank of the matrix
* Diagonal Elements
* Trace
* Eigen values
* Matrices obtained after Singular Value Decomposition
* Inverse if exists, otherwise Pseudo-Inverse
* Multiplication $Y$ with $X$
* Element-wise multiplication of $Y$ and its inverse(or pseudo-inverse)

In [9]:
np.random.seed(3)
Y = np.random.rand(10,10)
print(f'determinant of Y: {np.linalg.det(Y)}')
print(f'rank of the Y: {np.linalg.matrix_rank(Y)}')
print(f'diagonal elements of matrix Y: {Y.diagonal()}')
print(f'trace of matrix Y: {Y.trace()}')
print(f'eigen values of matrix Y: {np.linalg.eigvals(Y)}')
print(f'matrices obtained after svd: {np.linalg.svd(Y)}')
print(f'inverse of martix Y: {np.linalg.inv(Y)}')
print(f'multiplication of matrix Y with X i.e(Y*X): {np.matmul(Y, X)}')
print(f'Element-wise multiplication of  𝑌  and its inverse(or pseudo-inverse): {np.dot(Y, np.linalg.inv(Y))}')

determinant of Y: -0.012807808169095483
rank of the Y: 10
diagonal elements of matrix Y: [0.5507979  0.45683322 0.44045372 0.84575087 0.4576864  0.36217621
 0.06152893 0.19897603 0.92672568 0.19638058]
trace of matrix Y: 4.497309545724899
eigen values of matrix Y: [ 4.797525  +0.j          0.72411408+0.52238181j  0.72411408-0.52238181j
 -0.48250062+0.55413671j -0.48250062-0.55413671j -0.6909002 +0.j
 -0.25905659+0.32357377j -0.25905659-0.32357377j  0.2127855 +0.08352477j
  0.2127855 -0.08352477j]
matrices obtained after svd: (array([[-0.31776408, -0.02455508, -0.60644878, -0.17883359, -0.12672161,
         0.14873878, -0.17823942, -0.52859453, -0.02295855, -0.38570883],
       [-0.26118514, -0.10864541, -0.24911354,  0.26547359,  0.52168399,
        -0.25773901, -0.46995326,  0.21752636, -0.39285046,  0.16234491],
       [-0.31347907, -0.34483471, -0.25292297,  0.1214296 ,  0.1486964 ,
         0.33436315,  0.54080229,  0.48017168,  0.05660692, -0.20966421],
       [-0.35815379,  0.594

## End of Part - 1
 --- --- ---

## Part - 2
---
In this part, you will be working with the library ```pandas```. Import this library with an alias name ```pd```.

In [0]:
# Initial imports
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Download dataset from: http://biostat.mc.vanderbilt.edu/wiki/pub/Main/DataSets/titanic3.csv
Read the data and display the first 5 rows

In [11]:
#Download dataset from: http://biostat.mc.vanderbilt.edu/wiki/pub/Main/DataSets/titanic3.csv

file_url = "http://biostat.mc.vanderbilt.edu/wiki/pub/Main/DataSets/titanic3.csv"
df = pd.read_csv(file_url)
df.head()

pclass  survived  ...   body                        home.dest
0       1         1  ...    NaN                     St Louis, MO
1       1         1  ...    NaN  Montreal, PQ / Chesterville, ON
2       1         0  ...    NaN  Montreal, PQ / Chesterville, ON
3       1         0  ...  135.0  Montreal, PQ / Chesterville, ON
4       1         0  ...    NaN  Montreal, PQ / Chesterville, ON

[5 rows x 14 columns]

### Preprocessing of the Dataset



---


**1. Convert the categorical values of columns 'sex', 'embarked', 'pclass' into dummy values and add them into titanic_data_new DataFrame**




---



In [0]:
titanic_data_new = pd.get_dummies(df, columns=['sex', 'embarked', 'pclass'])
# titanic_data_new



---


**2. Fill the missing data in Age and Fare columns with the mean value of the respected column then add these columns to titanic_data_new**


---



In [0]:
age_mean = np.mean(titanic_data_new['age'])

fare_mean = np.mean(titanic_data_new['fare'])

titanic_data_new['new_age'] = titanic_data_new['age'].fillna(age_mean)
titanic_data_new['new_fare'] = titanic_data_new['fare'].fillna(fare_mean)

###Normalization


---



1. Normalize the columns which have numerical data



---



In [14]:
titanic_data_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 21 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   survived    1309 non-null   int64  
 1   name        1309 non-null   object 
 2   age         1046 non-null   float64
 3   sibsp       1309 non-null   int64  
 4   parch       1309 non-null   int64  
 5   ticket      1309 non-null   object 
 6   fare        1308 non-null   float64
 7   cabin       295 non-null    object 
 8   boat        486 non-null    object 
 9   body        121 non-null    float64
 10  home.dest   745 non-null    object 
 11  sex_female  1309 non-null   uint8  
 12  sex_male    1309 non-null   uint8  
 13  embarked_C  1309 non-null   uint8  
 14  embarked_Q  1309 non-null   uint8  
 15  embarked_S  1309 non-null   uint8  
 16  pclass_1    1309 non-null   uint8  
 17  pclass_2    1309 non-null   uint8  
 18  pclass_3    1309 non-null   uint8  
 19  new_age     1309 non-null  

In [15]:
# normalized_df=(titanic_data_new-titanic_data_new.mean())/titanic_data_new.std()
# normalized_df.head()
columns_to_be_normalized = ['new_age', 'sibsp', 'parch', 'new_fare']
for column in columns_to_be_normalized:
    titanic_data_new[f'normalized_{column}'] = (titanic_data_new[column]-titanic_data_new[column].mean())/titanic_data_new[column].std()
titanic_data_new.head()

survived  ... normalized_new_fare
0         1  ...            3.441165
1         1  ...            2.285603
2         0  ...            2.285603
3         0  ...            2.285603
4         0  ...            2.285603

[5 rows x 25 columns]



---
2. Drop the original age, fare columns
3. Append the normalized columns to the titanic_data_new DataFrame.



---



In [16]:
titanic_data_new = titanic_data_new.drop(columns=['age', 'fare'], axis=1)
titanic_data_new.head()

survived  ... normalized_new_fare
0         1  ...            3.441165
1         1  ...            2.285603
2         0  ...            2.285603
3         0  ...            2.285603
4         0  ...            2.285603

[5 rows x 23 columns]

###Plotting
1. plot the age against the ID(continuous)
2. plot the fare against the ID(scatter)

## End of Part - 2
---

## Part - 3
---

In this part, you will work with the library ```matplotlib```. Import the ```pyplot``` from ```matplotlib``` with an alias name ```plt```.

Plot the sine function with domain in $[-3\pi,3\pi]$. Label the axes appropriately. Add title $\sin(x)$. Use latex formatting while adding the title. Set the plot size to (10,10)

Plot $\sin(x)$ and its spectrum, $\cos(x)$ and its spectrum in a single plot, in the domain $[-2\pi,2\pi]$. Label the plot appropriately.

## End of Part - 3
---

Create a Github repository with the name ***SHALA2020*** and save this assignment there.